version: "3.9"
services:

  db_aiohttp:
    image: postgres:alpine3.20
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}